### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zhouyangtingwen** [zhouyangtingwen/ChatGPT-Stacks#1]
### Version 1.0.1

- [ ] Export conversations as PNG.
- [ ] Export conversations to Markdown, enabling migration to Obsidian and Notion, etc.
- [ ] Support keyword search within conversation pages.
- [ ] Automatic update
- [ ] Cancel spell checking in MacOs

😄 If you want more features, please write in this issue 👇

**Comment by iFwu** [comment]
我想增加一个使用统计功能，类似Github Profile页面的Calendar Heatmap
